apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: wide-ep-llm-d-prefill
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: Qwen3-235B-A22B-Instruct-2507-FP8
    llm-d.ai/role: prefill
spec:
  replicas: 0
  leaderWorkerTemplate:
    size: 2
    workerTemplate:
      metadata:
        labels:
          llm-d.ai/inferenceServing: "true"
          llm-d.ai/model: Qwen3-235B-A22B-Instruct-2507-FP8
          llm-d.ai/role: prefill
        annotations:
          k8s.v1.cni.cncf.io/networks: '[ { "name": "dhcp-network-port-1", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-2", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-3", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-4", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-5", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-6", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-7", "namespace": "llm-d-wide-ep" },                { "name": "dhcp-network-port-8", "namespace": "llm-d-wide-ep" }              ]'
      spec:
        #serviceAccountName: deepseek-r1
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 8Gi
          - name: hf-cache
            persistentVolumeClaim:
              claimName: model-pvc
          - name: rdma-discovery-script
            configMap:
              name: roce-hca-discovery-script
              defaultMode: 0755
          - name: podinfo
            downwardAPI:
              items:
                - path: "annotations"
                  fieldRef:
                    fieldPath: metadata.annotations
        containers:
        - name: vllm-worker
          #image: ghcr.io/llm-d/llm-d-cuda-dev:pr-274
          image: ghcr.io/llm-d/llm-d-dev:pr-245@sha256:06ba310cd557b7762c391ac11fe0bf20307851769bcf42973608ddcc3b4b47cf
          #image: ghcr.io/llm-d/llm-d-cuda-dev:pr-305@sha256:a5557be64a428817a66503bdbbc31709806aa41f45d2d64f0c4ada1bdd284814
          #image: ghcr.io/llm-d/llm-d-cuda-dev:pr-291@sha256:8aae57dc3fe157fed864fd174951e2ecf2a0652315ff5729463bf1ffdc0dc796
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
              - "IPC_LOCK"
              - "SYS_RAWIO"
              - "NET_RAW"
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
          args:
            - |-
              #################
              # RUN vLLM prefill worker
              #################
              sleep 20

              DISCOVERY_CMD="/scripts/discover.sh"
              if [[ -n "$REQUESTED_NICS" ]]; then
                DISCOVERY_CMD+=" -i $REQUESTED_NICS"
              fi
              
              $DISCOVERY_CMD
              source /data/vllm_env_${HOSTNAME}.sh

              KV_CONFIG_JSON="{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\",\"kv_ip\":\"${LOCAL_PRIMARY_IP}\"}"
              START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))
            
              source /opt/vllm/bin/activate
              
              # Qwen/Qwen3-235B-A22B-Instruct-2507-FP8 \
              exec vllm serve \
                Qwen/Qwen3-Coder-30B-A3B-Instruct \
                --port 8000 \
                --trust-remote-code \
                --disable-uvicorn-access-log \
                --data-parallel-hybrid-lb \
                --enable-expert-parallel \
                --tensor-parallel-size $TP_SIZE \
                --data-parallel-size $((LWS_GROUP_SIZE * DP_SIZE_LOCAL)) \
                --data-parallel-size-local $DP_SIZE_LOCAL \
                --data-parallel-address ${LWS_LEADER_ADDRESS} \
                --data-parallel-rpc-port 5555 \
                --data-parallel-start-rank $START_RANK \
                --gpu-memory-utilization 0.75
                --async-scheduling \
                --enable-eplb \
                --eplb-config '{"window_size":"1000","step_interval":"3000","num_redundant_experts":"32","log_balancedness":"False"}' \
                --max-model-len 32000
                #--kv_transfer_config "${KV_CONFIG_JSON}" \
                #--enable-dbo \
                #--dbo-prefill-token-threshold 32 \
          env:
          ### BOAZ SCRIPT
          - name: REDIS_HOST
            value: "redis-service.llm-d-wide-ep.svc.cluster.local"
          - name: REQUESTED_NICS
            value: "net1"
          - name: PRIMARY_IFNAME
            value: "net1"
          - name: SHARED_STORAGE_PATH
            value: "/data"
          #### END BOAZ SCRIPT CONFIG
          - name: HF_HUB_CACHE
            value: /huggingface-cache
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: llm-d-hf-token
                key: HF_TOKEN
          - name: VLLM_FUSED_MOE_CHUNK_SIZE
            value: "1024"
          - name: DP_SIZE_LOCAL
            value: "8"
          - name: TP_SIZE
            value: "1"
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: VLLM_ALL2ALL_BACKEND
            value: deepep_high_throughput
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: NVSHMEM_DEBUG
            value: "INFO" #TRACE
          - name: NVSHMEM_REMOTE_TRANSPORT
            value: "ibrc"
          - name: NVSHMEM_IB_ENABLE_IBGDA
            value: "true"
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: "net1"
          - name: NVSHMEM_IB_ADDR_RANGE
            value: "0.0.0.0/0"
          - name: NVSHMEM_HCA_LIST
            value: "mlx5_7:1"
          - name: NVSHMEM_ENABLE_NIC_PE_MAPPING
            value:  "1"
          - name: NVSHMEM_IB_GID_INDEX
            value: "3"
          - name: NVSHMEM_USE_IBGDA
            value: "1"
          - name: UCX_SOCKADDR_TLS_PRIORITY
            value: "tcp"
          - name: UCX_TLS
            value: "rc,sm,cuda_copy,cuda_ipc"
          - name: UCX_PROTO_INFO
            value: "y"
          - name: UCX_IB_GID_INDEX
            value: "3"
          - name: UCX_RC_MLX5_TM_ENABLE
            value: "n"
          - name: UCX_UD_MLX5_RX_QUEUE_LEN
            value: "1024"
          - name: GLOO_SOCKET_IFNAME
            value: "net1"
          - name: NCCL_SOCKET_IFNAME
            value: "net1"
          - name: NCCL_IB_HCA
            value: "mlx5_7:1"
          - name: NCCL_GDRCOPY_ENABLE
            value: "1"
          ports:
          - containerPort: 8000
            name: metrics
            protocol: TCP
          - containerPort: 5555
            name: rpc
            protocol: TCP
          resources:
            limits:
              memory: 512Gi
              ephemeral-storage: 64Gi
              nvidia.com/gpu: "8"
              nvidia.com/roce: "8"
            requests:
              cpu: 32
              memory: 512Gi
              ephemeral-storage: 64Gi
              nvidia.com/gpu: "8"
              nvidia.com/roce: "8"
          workingDir: /code
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /huggingface-cache
              name: hf-cache
            - name: hf-cache
              mountPath: /data
              subPath: debug-logs
            - mountPath: /etc/podnetinfo
              name: podinfo
            - name: rdma-discovery-script
              mountPath: /scripts
              readOnly: true

